import type { Metadata } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://marley-house.vercel.app';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of Service governing your use of The Marley Group digital platforms, including Marley Coffee, Lion Order, and RoMarley Beach House.',
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <article className="space-y-10">
      <header>
        <h1 className="text-[var(--gold)] font-display text-3xl sm:text-4xl font-semibold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-[var(--dim)] text-sm">Effective: June 2026</p>
      </header>

      {/* Acceptance */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          1. Acceptance of Terms
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          By accessing or using any website, application, or service operated by The Marley
          Group (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you agree to be
          bound by these Terms of Service. If you do not agree, you must discontinue use
          immediately.
        </p>
      </section>

      {/* Eligibility */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          2. Eligibility
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          General use of our platforms is available to individuals aged 13 and older. Access to
          cannabis-related content, products, and services — including all Lion Order pages and
          the King Clementine strain guide — is restricted to adults aged 21 and older. By
          accessing cannabis content, you confirm that you meet the legal age requirement in
          your jurisdiction.
        </p>
      </section>

      {/* User Conduct */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          3. User Conduct
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85 mb-3">
          You agree not to:
        </p>
        <ul className="text-[var(--cream)] text-sm leading-relaxed opacity-85 list-disc pl-5 space-y-1">
          <li>Use our services for any unlawful purpose</li>
          <li>Attempt to gain unauthorized access to any part of our systems</li>
          <li>Interfere with or disrupt the integrity or performance of our platforms</li>
          <li>Scrape, harvest, or collect data from our sites without written permission</li>
          <li>Impersonate any person or entity, or misrepresent your affiliation</li>
          <li>Upload or transmit viruses, malware, or other harmful code</li>
        </ul>
      </section>

      {/* Intellectual Property */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          4. Intellectual Property
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          All content, trademarks, logos, and intellectual property displayed on our platforms
          — including but not limited to &ldquo;Lion Order,&rdquo; &ldquo;Marley Coffee,&rdquo;
          &ldquo;RoMarley Beach House,&rdquo; the R-M monogram, and all associated visual
          assets — are owned by or licensed to The Marley Group. You may not reproduce,
          distribute, modify, or create derivative works from any of our content without prior
          written consent.
        </p>
      </section>

      {/* Cannabis Content Disclaimer */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          5. Cannabis Content Disclaimer
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          Cannabis-related content on our platforms is provided for informational and
          educational purposes only. It does not constitute medical, legal, or professional
          advice. Cannabis laws vary by jurisdiction; it is your sole responsibility to
          understand and comply with the laws in your area. We do not ship cannabis products
          across state lines or internationally.
        </p>
      </section>

      {/* AI Chat Disclaimer */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          6. AI Chat Disclaimer
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          &ldquo;Ask the House&rdquo; is an AI-powered assistant designed to provide general
          information about The Marley Group and its brands. Responses are generated by
          artificial intelligence and may contain inaccuracies. They do not represent the
          official views or advice of The Marley Group, Rohan Marley, or any affiliated entity.
          Do not rely on AI-generated responses for legal, medical, financial, or other
          professional decisions.
        </p>
      </section>

      {/* Limitation of Liability */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          7. Limitation of Liability
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          To the fullest extent permitted by law, The Marley Group and its officers, directors,
          employees, and agents shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of our services, including
          but not limited to loss of profits, data, or goodwill. Our total liability for any
          claim arising from these terms shall not exceed the amount you paid us, if any, in
          the twelve months preceding the claim.
        </p>
      </section>

      {/* Governing Law */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          8. Governing Law
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          These Terms shall be governed by and construed in accordance with the laws of the
          State of Florida, United States, without regard to its conflict-of-law principles.
        </p>
      </section>

      {/* Dispute Resolution */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          9. Dispute Resolution
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          Any dispute arising out of or related to these Terms shall first be attempted to be
          resolved through good-faith negotiation. If unresolved within 30 days, the dispute
          shall be submitted to binding arbitration in Miami-Dade County, Florida, under the
          rules of the American Arbitration Association. You agree to waive any right to a
          jury trial or to participate in a class action.
        </p>
      </section>

      {/* Changes */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          10. Changes to These Terms
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          We reserve the right to modify these Terms at any time. Material changes will be
          posted on this page with a revised effective date. Your continued use of our
          services after any changes constitutes acceptance of the updated terms.
        </p>
      </section>

      {/* Contact */}
      <section>
        <h2 className="text-[var(--gold)] font-display text-xl font-semibold mb-3">
          11. Contact
        </h2>
        <p className="text-[var(--cream)] text-sm leading-relaxed opacity-85">
          For questions about these Terms of Service, contact us at:{' '}
          <a href="mailto:legal@themarleygroup.com" className="text-[var(--gold)] hover:underline">
            legal@themarleygroup.com
          </a>
        </p>
      </section>
    </article>
  );
}
