import type { MerchItem } from '@/lib/types';

export const merch: MerchItem[] = [
  {
    id: 'lion-order-hoodie',
    name: 'Lion Order Hoodie',
    category: 'apparel',
    description: 'Heavyweight fleece hoodie. Embroidered lion crest on chest, "Lion Order" down the left sleeve. Oversized fit.',
    price: 85,
    image: '/merch/hoodie.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    badge: 'Bestseller',
    prototype: true,
  },
  {
    id: 'one-love-tee',
    name: 'One Love Tee',
    category: 'apparel',
    description: 'Organic cotton tee with screen-printed "One Love" script. Relaxed fit, pre-shrunk.',
    price: 42,
    image: '/merch/tee.jpg',
    sizes: ['S', 'M', 'L', 'XL'],
    prototype: true,
  },
  {
    id: 'legacy-crewneck',
    name: 'Legacy Crewneck',
    category: 'apparel',
    description: 'French terry crewneck with tone-on-tone Marley House emblem. Dropped shoulders, ribbed cuffs.',
    price: 72,
    image: '/merch/crewneck.jpg',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    prototype: true,
  },
  {
    id: 'zion-dad-cap',
    name: 'Zion Dad Cap',
    category: 'accessories',
    description: 'Washed cotton twill cap with embroidered lion silhouette. Adjustable brass buckle closure.',
    price: 34,
    image: '/merch/cap.jpg',
    badge: 'New',
    prototype: true,
  },
  {
    id: 'roots-beanie',
    name: 'Roots Beanie',
    category: 'accessories',
    description: 'Ribbed knit beanie with woven Marley House label. Cuffed fit, one size.',
    price: 28,
    image: '/merch/beanie.jpg',
    prototype: true,
  },
  {
    id: 'tuff-gong-tote',
    name: 'Tuff Gong Tote',
    category: 'accessories',
    description: 'Heavy-duty canvas tote with screen-printed Tuff Gong Records graphic. Reinforced handles.',
    price: 32,
    image: '/merch/tote.jpg',
    prototype: true,
  },
  {
    id: 'house-mug',
    name: 'The House Mug',
    category: 'home',
    description: 'Handcrafted ceramic mug, 12oz. Matte black exterior with gold Marley House mark. Microwave and dishwasher safe.',
    price: 24,
    image: '/merch/mug.jpg',
    badge: 'Bestseller',
    prototype: true,
  },
  {
    id: 'ritual-candle',
    name: 'Ritual Candle',
    category: 'home',
    description: 'Hand-poured soy candle — cedar, patchouli, and Jamaican coffee. 50-hour burn time. Reusable vessel.',
    price: 38,
    image: '/merch/candle.jpg',
    prototype: true,
  },
  {
    id: 'exodus-vinyl',
    name: 'Exodus Vinyl',
    category: 'music',
    description: '180g audiophile pressing. Remastered from original tapes. Gatefold sleeve with liner notes.',
    price: 36,
    image: '/merch/vinyl.jpg',
    badge: 'Limited',
    prototype: true,
  },
  {
    id: 'legend-art-print',
    name: 'Legend Art Print',
    category: 'music',
    description: 'Archival giclée print on heavyweight matte paper. 18×24". Numbered edition.',
    price: 48,
    image: '/merch/poster.jpg',
    badge: 'Limited',
    prototype: true,
  },
];
