import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'get-up-stand-up',
    name: 'Get Up, Stand Up',
    roast: 'Light',
    origin: 'Blend',
    notes: 'Bright, nutty, caramel notes',
    price: 16.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/get-up-stand-up.webp',
    prototype: true,
  },
  {
    id: 'one-love',
    name: 'One Love',
    roast: 'Medium',
    origin: 'Ethiopia',
    notes: '100% Ethiopian, balanced, smooth, exotic',
    price: 17.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    prototype: true,
  },
  {
    id: 'buffalo-soldier',
    name: 'Buffalo Soldier',
    roast: 'Medium-Dark',
    origin: 'Blend',
    notes: 'Rich, full-bodied, dark chocolate notes',
    price: 17.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/buffalo-soldier.webp',
    prototype: true,
  },
  {
    id: 'lively-up',
    name: 'Lively Up',
    roast: 'Dark',
    origin: 'Blend',
    notes: 'Bold, chocolate, subtle citrus',
    price: 16.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/lively-up.webp',
    prototype: true,
  },
  {
    id: 'simmer-down',
    name: 'Simmer Down',
    roast: 'Decaf (Swiss Water)',
    origin: 'Blend',
    notes: 'Balanced, hints of cocoa',
    price: 18.99,
    badges: ['Fairtrade Certified', 'Swiss Water Process'],
    image: '/products/simmer-down.webp',
    prototype: true,
  },
  {
    id: 'mystic-morning',
    name: 'Mystic Morning',
    roast: 'Medium',
    origin: 'Blend',
    notes: 'Smooth, balanced, legacy blend',
    price: 16.99,
    badges: ['Fairtrade Certified'],
    prototype: true,
  },
  {
    id: 'jamaican-blue-mountain',
    name: 'Jamaican Blue Mountain',
    roast: 'Premium Single Origin',
    origin: 'Jamaica',
    notes: 'Rare, smooth, refined complexity',
    price: 42.99,
    badges: ['Single Origin', 'Premium'],
    prototype: true,
  },
];
