import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'get-up-stand-up',
    name: 'Get Up, Stand Up',
    roast: 'Light',
    origin: 'Blend',
    notes: 'Bright, nutty, caramel notes',
    price: 16.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/get-up-stand-up.webp',
    prototype: true,
    description: 'A bright, uplifting blend that starts your day with purpose. Light-roasted to preserve delicate caramel and nut flavors.',
    brewingTip: 'Pour-over at 200°F for a clean, bright cup.',
    flavorProfile: [
      { label: 'Brightness', value: 5 },
      { label: 'Body', value: 2 },
      { label: 'Sweetness', value: 4 },
      { label: 'Complexity', value: 3 },
    ],
    pairing: 'Banana bread, fresh fruit, light pastries',
  },
  {
    id: 'one-love',
    name: 'One Love',
    roast: 'Medium',
    origin: 'Ethiopia',
    notes: '100% Ethiopian, balanced, smooth, exotic',
    price: 17.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/one-love.svg',
    prototype: true,
    description: '100% Ethiopian single-origin — smooth, balanced, and universally loved. The blend that brings everyone together.',
    brewingTip: 'French press, 4 minutes steep. Let the Ethiopian complexity unfold.',
    flavorProfile: [
      { label: 'Brightness', value: 3 },
      { label: 'Body', value: 3 },
      { label: 'Sweetness', value: 4 },
      { label: 'Complexity', value: 4 },
    ],
    pairing: 'Dark chocolate, almonds, warm spice cake',
    region: 'Sidamo, Ethiopia',
    elevation: '1,800–2,200m',
  },
  {
    id: 'buffalo-soldier',
    name: 'Buffalo Soldier',
    roast: 'Medium-Dark',
    origin: 'Blend',
    notes: 'Rich, full-bodied, dark chocolate notes',
    price: 17.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/buffalo-soldier.webp',
    prototype: true,
    description: 'A bold, fearless blend with deep dark chocolate notes. Medium-dark roasted for those who like their coffee with backbone.',
    brewingTip: 'Espresso or Moka pot — let the richness concentrate.',
    flavorProfile: [
      { label: 'Brightness', value: 2 },
      { label: 'Body', value: 5 },
      { label: 'Sweetness', value: 3 },
      { label: 'Complexity', value: 4 },
    ],
    pairing: 'Dark chocolate, aged cheese, smoked meats',
  },
  {
    id: 'lively-up',
    name: 'Lively Up',
    roast: 'Dark',
    origin: 'Blend',
    notes: 'Bold, chocolate, subtle citrus',
    price: 16.99,
    badges: ['Fairtrade Certified', 'One Tree Planted'],
    image: '/products/lively-up.webp',
    prototype: true,
    description: 'Full-throttle dark roast with a surprising citrus finish. For the ones who need no introduction.',
    brewingTip: 'Drip or cold brew. 24-hour cold brew unlocks hidden citrus.',
    flavorProfile: [
      { label: 'Brightness', value: 2 },
      { label: 'Body', value: 5 },
      { label: 'Sweetness', value: 2 },
      { label: 'Complexity', value: 4 },
    ],
    pairing: 'Dark chocolate truffles, orange peel, espresso martini',
  },
  {
    id: 'simmer-down',
    name: 'Simmer Down',
    roast: 'Decaf (Swiss Water)',
    origin: 'Blend',
    notes: 'Balanced, hints of cocoa',
    price: 18.99,
    badges: ['Fairtrade Certified', 'Swiss Water Process'],
    image: '/products/simmer-down.webp',
    prototype: true,
    description: 'Swiss Water Process decaf that refuses to compromise on flavor. All the ritual, none of the buzz.',
    brewingTip: 'Any method works. Treat it exactly like regular coffee.',
    flavorProfile: [
      { label: 'Brightness', value: 3 },
      { label: 'Body', value: 3 },
      { label: 'Sweetness', value: 4 },
      { label: 'Complexity', value: 3 },
    ],
    pairing: 'Evening desserts, vanilla ice cream, biscotti',
  },
  {
    id: 'mystic-morning',
    name: 'Mystic Morning',
    roast: 'Medium',
    origin: 'Blend',
    notes: 'Smooth, balanced, legacy blend',
    price: 16.99,
    badges: ['Fairtrade Certified'],
    image: '/products/mystic-morning.svg',
    prototype: true,
    description: 'A contemplative, smooth blend for quiet mornings. The legacy recipe — balanced and timeless.',
    brewingTip: 'Pour-over or drip. Best enjoyed without milk to taste the full profile.',
    flavorProfile: [
      { label: 'Brightness', value: 3 },
      { label: 'Body', value: 3 },
      { label: 'Sweetness', value: 3 },
      { label: 'Complexity', value: 3 },
    ],
    pairing: 'Toast with honey, yogurt, morning meditation',
  },
  {
    id: 'jamaican-blue-mountain',
    name: 'Jamaican Blue Mountain',
    roast: 'Premium Single Origin',
    origin: 'Jamaica',
    notes: 'Rare, smooth, refined complexity',
    price: 42.99,
    badges: ['Single Origin', 'Premium'],
    image: '/products/jamaican-blue-mountain.svg',
    prototype: true,
    description: 'One of the world\'s rarest and most sought-after coffees. Grown at elevation in Jamaica\'s Blue Mountains, hand-picked and sun-dried. Refined complexity with zero bitterness.',
    brewingTip: 'Pour-over with precision: 200°F, 1:16 ratio. This coffee deserves attention.',
    flavorProfile: [
      { label: 'Brightness', value: 4 },
      { label: 'Body', value: 4 },
      { label: 'Sweetness', value: 5 },
      { label: 'Complexity', value: 5 },
    ],
    pairing: 'On its own. Or with the finest dark chocolate.',
    region: 'Blue Mountains, Jamaica',
    elevation: '900–1,700m',
  },
];
