import type { VideoRef } from '@/lib/types';

// ── Brand Films & Origin Stories ──────────────────────────────
export const storyVideos: VideoRef[] = [
  {
    id: 'marley-coffee-brand-film',
    title: 'Marley Coffee Brand Film',
    source: 'youtube',
    videoId: 'XE-uV_DsurA',
    channel: 'Marley Coffee',
    category: 'story',
  },
  {
    id: 'rooted-in-legacy',
    title: 'Rooted in Legacy — The Marley Coffee Story',
    source: 'youtube',
    videoId: '112LQ_4P9rI',
    channel: 'Marley Coffee',
    category: 'story',
  },
  {
    id: 'marley-coffee-story',
    title: 'The Marley Coffee Story',
    source: 'youtube',
    videoId: 'vkkJycAr45E',
    channel: 'Marley Coffee',
    category: 'story',
  },
  {
    id: 'bob-inspires-coffee',
    title: 'Bob Marley Inspires Son\'s Coffee Startup',
    source: 'youtube',
    videoId: 'OwNLYwn15V4',
    category: 'story',
  },
  {
    id: 'launches-coffee-line',
    title: 'Son of Bob Marley, Rohan Marley Launches Own Coffee Line',
    source: 'youtube',
    videoId: 'CJYbmA3V9rU',
    category: 'story',
  },
];

// ── House Sessions Playlist ───────────────────────────────────
export const sessionsPlaylist: VideoRef = {
  id: 'house-sessions-playlist',
  title: 'House Sessions — Preparaciones',
  source: 'youtube',
  playlistId: 'PLC7UTUpH-pK182kGnMXGHcutFSDNYZrYP',
  channel: 'Marley Coffee Latam',
  category: 'sessions',
};

// ── Podcasts & Long-Form Conversations ────────────────────────
export const podcastVideos: VideoRef[] = [
  {
    id: 'drink-champs',
    title: 'Rohan Marley — Bob Marley, Rastafari, Family & Legacy | Drink Champs',
    source: 'youtube',
    videoId: 'X0SZf3r63ls',
    channel: 'Drink Champs',
    category: 'podcast',
  },
  {
    id: 'i-am-athlete',
    title: 'Life as Bob Marley\'s Son, Lauryn Hill & Playing Football | I AM ATHLETE',
    source: 'youtube',
    videoId: 'hBd-JIpdc50',
    channel: 'I AM ATHLETE',
    category: 'podcast',
  },
  {
    id: 'pivot-podcast',
    title: '"When My Father Passed Away… We Had No Money" | The Pivot Podcast',
    source: 'youtube',
    videoId: 'rhgStTzkeUo',
    channel: 'The Pivot Podcast',
    category: 'podcast',
  },
  {
    id: 'we-in-miami',
    title: 'Rohan Marley Exclusive — We In Miami Podcast Ep. 43',
    source: 'youtube',
    videoId: 'WY1tP2qy7Vg',
    channel: 'We In Miami Podcast',
    category: 'podcast',
  },
  {
    id: 'more-than-a-title',
    title: 'Bob Marley, Rastafari, Family & Spirituality | More Than A Title',
    source: 'youtube',
    videoId: 'XLaevehZqqQ',
    channel: 'More Than A Title',
    category: 'podcast',
  },
  {
    id: 'when-legends-speak',
    title: 'Lessons From Rastafari, Faith, Family & Legacy | When Legends Speak',
    source: 'youtube',
    videoId: 'truabWu_rHc',
    channel: 'When Legends Speak',
    category: 'podcast',
  },
  {
    id: 'create-the-life',
    title: 'Create the Life Podcast — Hosted by Edgerrin James',
    source: 'youtube',
    videoId: 'iDO68MSfEIo',
    channel: 'Create the Life Podcast',
    category: 'podcast',
  },
  {
    id: 'family-legacy-podcast',
    title: 'Family Legacy, Relationship with Lauryn Hill & Miami Football',
    source: 'youtube',
    videoId: 'H_QYV2quMgM',
    category: 'podcast',
  },
  {
    id: 'deep-lauryn-hill',
    title: 'Rohan Gets Deep About Lauryn Hill, YG & Standing Up To The System',
    source: 'youtube',
    videoId: 'ygnZmsj05iw',
    category: 'podcast',
  },
  {
    id: 'business-ventures',
    title: 'Business Experiences & Newest Venture with Rohan Marley',
    source: 'youtube',
    videoId: 'Z9C7Z53zMOQ',
    category: 'podcast',
  },
  {
    id: 'deriq-king',
    title: 'Former Miami LB Rohan Marley Joins D\'eriq King',
    source: 'youtube',
    videoId: '5K4F-7M97pg',
    category: 'podcast',
  },
  {
    id: 'drink-champs-rastafari',
    title: 'The Way of Life of Rastafari | Drink Champs',
    source: 'youtube',
    videoId: 'IgLDgPF1lHA',
    channel: 'Drink Champs',
    category: 'podcast',
  },
  {
    id: 'drink-champs-name',
    title: 'Carrying the Marley Name | Drink Champs',
    source: 'youtube',
    videoId: 'LV9ZZCZ7fIs',
    channel: 'Drink Champs',
    category: 'podcast',
  },
];

// ── Interviews ────────────────────────────────────────────────
export const interviewVideos: VideoRef[] = [
  {
    id: 'one-love-film',
    title: 'Honoring Bob Marley in "One Love"',
    source: 'youtube',
    videoId: '1vjUHbZ0tu8',
    category: 'interview',
  },
  {
    id: 'one-love-sileo',
    title: 'Bob Marley Film "One Love", Legacy & Super Bowl | Dan Sileo',
    source: 'youtube',
    videoId: 'F0hSiUyDZhI',
    category: 'interview',
  },
  {
    id: 'one-love-boxoffice',
    title: 'Reacts to Bob Marley One Love Box Office',
    source: 'youtube',
    videoId: 'AWYlqObCVDU',
    category: 'interview',
  },
  {
    id: 'before-the-fame',
    title: 'Rohan Marley | Before The Fame',
    source: 'youtube',
    videoId: 'TY4e5zSRECs',
    channel: 'FOX SOUL',
    category: 'interview',
  },
  {
    id: 'family-business-philosophy',
    title: 'Family Legacy, Business Strategy & Life Philosophy',
    source: 'youtube',
    videoId: '6HXVLXURggs',
    category: 'interview',
  },
  {
    id: 'bob-70th-birthday',
    title: 'Bob Marley 70th Birthday Celebration — Jamaica 2015',
    source: 'youtube',
    videoId: 'SgMWPwD7klk',
    category: 'interview',
  },
  {
    id: 'celebs-documentary',
    title: 'Neville Garrick & Rohan Marley — "Marley" Documentary',
    source: 'youtube',
    videoId: 's_rWT2UuxUA',
    channel: 'Celebs.com',
    category: 'interview',
  },
  {
    id: 'meeting-lauryn',
    title: 'From Roadie to 5 Kids — Meeting Lauryn Hill in 1996',
    source: 'youtube',
    videoId: 'yyk-U1K--Vk',
    category: 'interview',
  },
  {
    id: 'defending-lauryn',
    title: 'Rohan Marley Goes Off Defending Ex-Wife Lauryn Hill',
    source: 'youtube',
    videoId: 'aBm9pts2-Sg',
    category: 'interview',
  },
  {
    id: 'michael-jackson',
    title: 'They Asked Michael Jackson For Help When Bob Passed Away',
    source: 'youtube',
    videoId: 'rbYlaym65BM',
    category: 'interview',
  },
  {
    id: 'cannabis-michigan',
    title: 'Rohan Marley Launches Cannabis Line in Michigan',
    source: 'youtube',
    videoId: 'APq_Gs9vC6M',
    category: 'interview',
  },
  {
    id: 'all-things-cannabis',
    title: 'Rohan Marley — All Things Cannabis',
    source: 'youtube',
    videoId: 'onyaPdTYIlI',
    category: 'interview',
  },
  {
    id: 'glad-back-miami',
    title: 'Rohan Marley Glad To Be Back at Miami',
    source: 'youtube',
    videoId: '8oI0zFgRggo',
    category: 'interview',
  },
  {
    id: 'nfl-network',
    title: 'Rohan Marley on NFL Network Total Access',
    source: 'youtube',
    videoId: 'WRu9oJy4zMk',
    channel: 'NFL Network',
    category: 'interview',
  },
  {
    id: 'miramar-first-fridays',
    title: 'Entrepreneurial Journey at Miramar First Fridays',
    source: 'youtube',
    videoId: 'nT1ZVoC_QEU',
    category: 'interview',
  },
  {
    id: 'inside-miami-life',
    title: 'Inside Rohan Marley\'s Miami Life — Family Values, Business',
    source: 'youtube',
    videoId: 'vzhplWUj7z4',
    category: 'interview',
  },
  {
    id: '420-live',
    title: 'Bob Marley, Nico Marley Talks Lion X CBD | 420LIVE',
    source: 'youtube',
    videoId: 'wlftBRPMv8A',
    category: 'interview',
  },
  {
    id: 'whats-trending',
    title: 'Inside the House of Marley | What\'s Trending LIVE',
    source: 'youtube',
    videoId: 'qAXwRZLHEks',
    channel: "What's Trending",
    category: 'interview',
  },
];

// ── Coffee ────────────────────────────────────────────────────
export const coffeeVideos: VideoRef[] = [
  {
    id: 'marley-coffee-feat',
    title: 'Marley Coffee (feat. Rohan Marley)',
    source: 'youtube',
    videoId: 'ppGy5k3RtaQ',
    channel: 'Marley Coffee',
    category: 'coffee',
  },
  {
    id: 'weissman-rohan',
    title: 'Marley Coffee — Andrew Weissman & Rohan Marley',
    source: 'youtube',
    videoId: 'GxuNq6LlHqk',
    category: 'coffee',
  },
  {
    id: 'shopcom-coffee-break',
    title: 'Marley Coffee Break with Rohan Marley | SHOP.COM',
    source: 'youtube',
    videoId: 'QZ2WNklPsNQ',
    channel: 'SHOP.COM',
    category: 'coffee',
  },
  {
    id: 'visits-chile',
    title: 'Rohan Visits Marley Coffee Chile',
    source: 'youtube',
    videoId: 'tgDx7NsaXGg',
    channel: 'Marley Coffee',
    category: 'coffee',
  },
  {
    id: 'coffee-cookbook',
    title: 'Coffee Cookbook With Chef Max Hardy',
    source: 'youtube',
    videoId: '6ZmgpGt2Xg8',
    channel: 'Am Media Group',
    category: 'coffee',
  },
  {
    id: 'talks-marley-coffee',
    title: 'Rohan Marley Talks About Marley Coffee',
    source: 'youtube',
    videoId: '0hlZgXK7j84',
    channel: 'Marley Coffee',
    category: 'coffee',
  },
  {
    id: 'chasing-coffee-jamaica',
    title: 'Marley Coffee Jamaica — Chasing Coffee',
    source: 'youtube',
    videoId: 'shCxZsiRS6g',
    category: 'coffee',
  },
  {
    id: 'visits-markcol',
    title: 'Rohan Marley of Marley Coffee Visits Markcol',
    source: 'youtube',
    videoId: 'gX8woIxJFXs',
    category: 'coffee',
  },
  {
    id: 'inthemixx',
    title: 'Rohan Marley on Marley Coffee | InTheMixx',
    source: 'youtube',
    videoId: 'CWW5_PywlqA',
    category: 'coffee',
  },
  {
    id: 'blue-mountain-coffee',
    title: 'Blue Mountain Coffee | Taste of Marley E4',
    source: 'youtube',
    videoId: 'Bd4SvSZ3q30',
    channel: 'Our Taste',
    category: 'coffee',
  },
  {
    id: 'organic-movement',
    title: 'The Organic Movement',
    source: 'youtube',
    videoId: 'DUNIIMPVNBg',
    category: 'coffee',
  },
];

// ── Taste of Marley Series ────────────────────────────────────
export const tasteVideos: VideoRef[] = [
  {
    id: 'taste-full-series',
    title: 'Taste of Marley — Full Series',
    source: 'youtube',
    videoId: 'dw18Cdj9A2I',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-ep1',
    title: 'What Jamaica is REALLY Like [4K] | EP 1',
    source: 'youtube',
    videoId: '4C7jwbF0yE0',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-ep2',
    title: 'Journey to the Heart of Jamaica [4K] | EP 2',
    source: 'youtube',
    videoId: '68MYtwwfeEo',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-ep3',
    title: 'Living Like Bob Marley — A Day with Rohan [4K] | EP 3',
    source: 'youtube',
    videoId: 'wpfs_l6HHtk',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-ep3-alt',
    title: 'Jamaica\'s Island Flavors & Natural Living [4K]',
    source: 'youtube',
    videoId: '2t5AKPKe_cA',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-e1-cookout',
    title: 'Cookout Party in Jah Land | E1',
    source: 'youtube',
    videoId: 'elAOCkhN2XI',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-e2-stush',
    title: '\'Stush\' And The Sea | E2',
    source: 'youtube',
    videoId: 'HAcAR6ZgD-w',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-e5-rum',
    title: 'Drinking 71% Jamaican Rum | E5',
    source: 'youtube',
    videoId: '0nQVn0jTQg0',
    channel: 'Our Taste',
    category: 'taste',
  },
  {
    id: 'taste-e10-finale',
    title: 'Jamaica\'s Next Generation — Finale | E10',
    source: 'youtube',
    videoId: '3jV0iulViQM',
    channel: 'Our Taste',
    category: 'taste',
  },
];

// ── Football ──────────────────────────────────────────────────
export const footballVideos: VideoRef[] = [
  {
    id: 'stories-of-the-u',
    title: 'Rohan Marley — Stories Of The U',
    source: 'youtube',
    videoId: 'ogZDby-8cOo',
    channel: 'Stories Of The U',
    category: 'football',
  },
  {
    id: 'proved-doubters-wrong',
    title: 'How Rohan Marley Proved Football Doubters Wrong At Miami',
    source: 'youtube',
    videoId: '23aLDedhMKI',
    category: 'football',
  },
  {
    id: 'beast-at-miami',
    title: 'Bob Marley\'s Son Was a BEAST at Miami — All-Conference',
    source: 'youtube',
    videoId: 'CEg7qD5Cpuw',
    category: 'football',
  },
  {
    id: 'football-reel',
    title: 'Rohan Marley Football Reel',
    source: 'youtube',
    videoId: 'ILuL3c4G5jA',
    category: 'football',
  },
  {
    id: 'ray-lewis-rohan',
    title: 'Miami Hurricanes — Ray Lewis & Rohan Marley',
    source: 'youtube',
    videoId: 'qHBDMW4dyT8',
    category: 'football',
  },
  {
    id: 'rookie-year',
    title: 'Rohan Talks About His Rookie Year in Pro Football',
    source: 'youtube',
    videoId: '0FBxW8blyB0',
    category: 'football',
  },
];

// ── Music & Family Legacy ─────────────────────────────────────
export const musicVideos: VideoRef[] = [
  {
    id: 'yg-praise-jah',
    title: 'YG Marley — Praise Jah in the Moonlight',
    source: 'youtube',
    videoId: 'cDpEzmYx0qs',
    category: 'music',
  },
  {
    id: 'yg-rohan-singing',
    title: 'YG Marley with Rohan (His Dad) Singing Together',
    source: 'youtube',
    videoId: 'eRIZqyqvKbI',
    category: 'music',
  },
  {
    id: 'korean-reggae',
    title: 'Korean Reggae (With Rohan Marley)',
    source: 'youtube',
    videoId: '9qcfihNPI6M',
    category: 'music',
  },
  {
    id: 'africa-road-trip',
    title: 'Ziggy, Robbie & Rohan — Marley Africa Road Trip',
    source: 'youtube',
    videoId: 'XJ8FmHoaEcI',
    category: 'music',
  },
  {
    id: 'jamaica-ethiopia',
    title: 'The Deep Roots Binding Jamaica and Ethiopia',
    source: 'youtube',
    videoId: 'xrSS0ehYrVo',
    category: 'music',
  },
  {
    id: 'daughter-part1',
    title: 'Rohan & Lauryn Hill\'s Daughter on Their Relationship — Pt. 1',
    source: 'youtube',
    videoId: 'Uy6LKPFN_WM',
    category: 'music',
  },
  {
    id: 'daughter-part2',
    title: 'Rohan & Lauryn Hill\'s Daughter on Their Relationship — Pt. 2',
    source: 'youtube',
    videoId: '49J0o__25PU',
    category: 'music',
  },
];

// ── Ventures & Lifestyle ──────────────────────────────────────
export const lifestyleVideos: VideoRef[] = [
  {
    id: 'materials-matter',
    title: 'The Foundation — Legacy & House of Marley | #MaterialsMatter',
    source: 'youtube',
    videoId: 'xNLKSx2efSQ',
    channel: 'House of Marley',
    category: 'lifestyle',
  },
  {
    id: 'karmaloop',
    title: 'Rohan Marley for the House of Marley | KarmaloopTV',
    source: 'youtube',
    videoId: 'kmtSW4otiC0',
    channel: 'KarmaloopTV',
    category: 'lifestyle',
  },
  {
    id: 'hom-feature',
    title: 'The House of Marley feat. Rohan Marley',
    source: 'youtube',
    videoId: 'visWfc5VUZk',
    category: 'lifestyle',
  },
  {
    id: 'lion-order',
    title: 'Rohan Marley — Lion Order Movement',
    source: 'youtube',
    videoId: 'WoJrJQZEysg',
    category: 'lifestyle',
  },
  {
    id: 'cannabis-revolution',
    title: 'Bob Marley\'s Cannabis Revolution — Legacy of Lion Order',
    source: 'youtube',
    videoId: '6YL7DneCa_g',
    category: 'lifestyle',
  },
  {
    id: 'nomad-joakim',
    title: 'NOMAD — Joakim Noah Tours Jamaica with Rohan Marley',
    source: 'youtube',
    videoId: 'oTYe3MZDinA',
    channel: 'NBA',
    category: 'lifestyle',
  },
  {
    id: 'eco-headphones',
    title: 'House of Marley Eco-Friendly Headphones',
    source: 'youtube',
    videoId: 'DFKMgowGTZg',
    category: 'lifestyle',
  },
  {
    id: 'ces-2018',
    title: 'House of Marley at CES 2018',
    source: 'youtube',
    videoId: 'bc75c8pvpo4',
    category: 'lifestyle',
  },
  {
    id: 'ces-2012',
    title: 'House of Marley at CES 2012 — Rohan Talks to Martin Stanford',
    source: 'youtube',
    videoId: 'R4jteAfspv0',
    category: 'lifestyle',
  },
  {
    id: 'regenerative-therapy',
    title: '1 Year After Injury — How Regenerative Therapy Helped Recovery',
    source: 'youtube',
    videoId: 'uTbieWsmBtA',
    category: 'lifestyle',
  },
];

// ── All videos flat (for search/filtering) ────────────────────
export const allVideos: VideoRef[] = [
  sessionsPlaylist,
  ...storyVideos,
  ...podcastVideos,
  ...interviewVideos,
  ...coffeeVideos,
  ...tasteVideos,
  ...footballVideos,
  ...musicVideos,
  ...lifestyleVideos,
];

// ── Channels ──────────────────────────────────────────────────
export const channels = [
  { name: 'Rohan Marley', url: 'https://www.youtube.com/@MrRohanmarley' },
  { name: 'Marley Coffee Latam', url: 'https://www.youtube.com/@MarleyCoffeeLatam' },
  { name: 'Tuff Gong Television', url: 'https://www.youtube.com/user/TuffGongTelevision' },
  { name: 'House of Marley', url: 'https://www.youtube.com/user/TheHouseofMarley' },
];
